services:
  frontend-web:
    build:
      context: .
      dockerfile: docker/dockerfile
      args:
        APP_ENV: ${APP_ENV:-development}

    environment:
      APP_ENV: ${APP_ENV:-development}

    volumes:
      - .:/app
      - /app/node_modules

    ports:
      - "3000:3000"
